# Generated by Django 4.2.13 on 2024-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurs adını yazınız.', max_length=100, unique=True, verbose_name='Kurs Adı')),
                ('description', models.TextField(blank=True, help_text='Kurs açıklamasını yazınız.', null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(default='courses/default_courses_image.jpg', help_text='Kurs resmini yükleyiniz.', upload_to='courses/%Y/%m/%d/', verbose_name='Kurs Resmi')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Kursun oluşturulma tarihini gösterir.', verbose_name='Oluşturulma Tarihi')),
                ('available', models.BooleanField(default=True, help_text='Kursun kullanılabilir olup olmadığını belirtir.', verbose_name='Kullanılabilirlik')),
            ],
        ),
    ]
